USE Shop_Db;


SELECT TOV.NTOV, SUM(CASE WHEN DMZ.PR = 1 THEN + DMS.KOL ELSE - DMS.KOL END) as leftOverlAmount, SUM(CASE WHEN DMZ.PR = 1 THEN + (DMS.KOL*DMS.CENA) ELSE - (DMS.KOL*DMS.CENA) END) as leftOverInUSD
FROM TOV
INNER JOIN DMS
ON TOV.KTOV = DMS.KTOV
INNER JOIN DMZ
ON DMS.NDM = DMZ.NDM
GROUP BY NTOV
ORDER BY NTOV