WITH mx AS 
(SELECT * FROM DMS WHERE NDM IN (SELECT MAX(NDM) FROM DMS)),
mn AS
(SELECT * FROM DMS WHERE NDM IN (SELECT MIN(NDM) FROM DMS))
INSERT INTO DMS (KTOV,NDM,KOL,CENA,SORT)
SELECT KTOV,NDM,KOL,CENA,SORT FROM mx WHERE NOT EXISTS (SELECT * FROM mn WHERE mn.KTOV = mx.KTOV)
UNION 
SELECT KTOV,(SELECT MAX(NDM) FROM DMS),KOL,CENA,SORT FROM mn WHERE NOT EXISTS (SELECT * FROM mx WHERE mn.KTOV = mx.KTOV);