USE Shop_Db;

SELECT	TOV.NTOV, DMS.KOL, SUM(DMS.CENA * DMS.KOL) AS saleVolume
FROM TOV
INNER JOIN DMS
ON TOV.KTOV = DMS.KTOV
INNER JOIN DMZ
ON DMS.NDM = DMZ.NDM
WHERE DMZ.DDM = '2014.01.05' AND DMZ.PR = 1
GROUP BY TOV.NTOV, TOV.Sort, DMS.KOL
ORDER BY saleVolume DESC
